import { readFileSync } from "node:fs";

const actionGroupsJson = readFileSync(new URL("../../renderer/catalog/action-groups.json", import.meta.url), "utf8");
export const actionGroupsSource = `window.O_PET_ACTION_GROUPS = ${actionGroupsJson};`;
export const pageStartSource = readFileSync(new URL("../../renderer/page-start.html", import.meta.url), "utf8");
export const pageEndSource = readFileSync(new URL("../../renderer/page-end.html", import.meta.url), "utf8");
export const hostSource = readFileSync(new URL("../../renderer/host.js", import.meta.url), "utf8");
export const particlesSource = readFileSync(new URL("../../renderer/view/particles.js", import.meta.url), "utf8");
export const schedulerSource = readFileSync(new URL("../../renderer/runtime/scheduler.js", import.meta.url), "utf8");
export const timelineSource = readFileSync(new URL("../../renderer/runtime/timeline.js", import.meta.url), "utf8");
export const presenterSource = readFileSync(new URL("../../renderer/runtime/presenter.js", import.meta.url), "utf8");
export const activitiesSource = readFileSync(new URL("../../renderer/behaviors/activities.js", import.meta.url), "utf8");
export const idleSource = readFileSync(new URL("../../renderer/behaviors/idle.js", import.meta.url), "utf8");
export const cuesSource = readFileSync(new URL("../../renderer/behaviors/cues.js", import.meta.url), "utf8");
export const interactionSource = readFileSync(new URL("../../renderer/behaviors/interaction.js", import.meta.url), "utf8");
export const pointerSource = readFileSync(new URL("../../renderer/adapters/pointer.js", import.meta.url), "utf8");
export const preferencesSource = readFileSync(new URL("../../renderer/adapters/preferences.js", import.meta.url), "utf8");
export const actionsSource = readFileSync(new URL("../../renderer/engine/actions.js", import.meta.url), "utf8");
export const visualChannelsSource = readFileSync(new URL("../../renderer/engine/visual-channels.js", import.meta.url), "utf8");
export const runtimeSource = readFileSync(new URL("../../renderer/engine/runtime.js", import.meta.url), "utf8");
export const choreographySource = readFileSync(new URL("../../renderer/engine/channels/choreography.js", import.meta.url), "utf8");
export const effectsSource = readFileSync(new URL("../../renderer/view/effects.js", import.meta.url), "utf8");
export const eyesSource = readFileSync(new URL("../../renderer/view/eyes.js", import.meta.url), "utf8");
export const renderSource = readFileSync(new URL("../../renderer/view/svg.js", import.meta.url), "utf8");
export const geometrySource = readFileSync(new URL("../../renderer/view/geometry-data.js", import.meta.url), "utf8");
export const geometryEngineSource = readFileSync(new URL("../../renderer/view/geometry.js", import.meta.url), "utf8");
export const mathSource = readFileSync(new URL("../../renderer/engine/math.js", import.meta.url), "utf8");
export const motionSource = readFileSync(new URL("../../renderer/engine/channels/motion.js", import.meta.url), "utf8");
export const expressionSource = readFileSync(new URL("../../renderer/engine/channels/expression.js", import.meta.url), "utf8");
export const gazeSource = readFileSync(new URL("../../renderer/engine/channels/gaze.js", import.meta.url), "utf8");
export const presetsSource = readFileSync(new URL("../../renderer/catalog/presets.js", import.meta.url), "utf8");
export const sequencesSource = readFileSync(new URL("../../renderer/catalog/sequences.js", import.meta.url), "utf8");
export const tablesSource = readFileSync(new URL("../../renderer/catalog/tables.js", import.meta.url), "utf8");
